import { SectionType } from "../../types.js";
import { reverseObject } from "../../utils.js";

export default reverseObject({
	description: "Description",
	glyphOrigin: "Köken",
	etymology: "Köken",
	pronunciation: "Söyleniş",
	production: "Production",
	usageNotes: "Usage notes",
	reconstructionNotes: "Reconstruction notes",
	inflection: "Inflection",
	conjugation: "Conjugation",
	declension: "Declension",
	mutation: "Mutation",
	quotations: "Quotations",
	alternativeForms: "Alternative forms",
	alternativeReconstructions: "Alternative reconstructions",
	synonyms: "Synonyms",
	antonyms: "Antonyms",
	hypernyms: "Hypernyms",
	hyponyms: "Hyponyms",
	meronyms: "Meronyms",
	holonyms: "Holonyms",
	comeronyms: "Comeronyms",
	troponyms: "Troponyms",
	parasynonyms: "Parasynonyms",
	coordinate: "Coordinate terms",
	derived: "Türetilmiş kavramlar",
	related: "Related terms",
	collocations: "Collocations",
	descendants: "Descendants",
	translations: "Translations",
	trivia: "Trivia",
	seeAlso: "Ek Okumalar",
	references: "Kaynakça",
	furtherReading: "Further reading",
	anagrams: "Anagramlar",
	definitions: "Definitions",
	examples: "Examples",
} satisfies Record<SectionType, string> as Record<SectionType, string>);
